### ISSUE TITLE
problem with adding an app

### ISSUE THREAD

**Issue by alfiswielki** [npwd-community/npwd_qb_garage#11]
hello I upload everything the phone works, I try to add a garage and this is where the problems start....
I add the garage app to config.json and yet it is not on the phone and under f8 I have this, I will add a picture

How to do it? I am using the new qbcore

![telefon1](https://user-images.githubusercontent.com/111529419/192115359-731b1f84-c2f3-48f1-9386-6164e35148cc.png)
![telefon2](https://user-images.githubusercontent.com/111529419/192115363-8fdb9916-c148-48d2-a7d3-1ae4ce761ca0.png)
![telefon3](https://user-images.githubusercontent.com/111529419/192115369-8a5d4868-576f-4665-a30e-a0d28b91556b.png)

**Comment by alfiswielki** [comment]
I could not find any information about this....

**Comment by alfiswielki** [comment]
solved can be closed

**Comment by alfiswielki** [comment]
![err](https://user-images.githubusercontent.com/111529419/192116498-d02b2ae2-4a6d-417f-9992-943ebed30132.png)
I still have the problem of running multiple applications.... only the first one on the list always works....

**Comment by SamShanks1** [comment]
Could you make a support thread in the PE discord 
https://discord.gg/EnyXZrgZ
