### ISSUE TITLE
jdev's garage support (other ones too i guess but idc about 'em)

### ISSUE THREAD

**Issue by TonybynMp4** [npwd-community/npwd_qb_garage#3]
i can do the jdev thing if you send the parkingspot and state to requestWaypoint (also needs to be able to locate garaged vehicles)

(for tracking vehicles in garage)

**Comment by McNastty6699** [comment]
did this ever get fixed. i use jdevs garage too but cant get it working with the phone

**Comment by TonybynMp4** [comment]
> did this ever get fixed. i use jdevs garage too but cant get it working with the phone

nah it's on a long list of stuff @SamShanks1 needs to do and he seem to have died i think idk
